Added functionality to copy specific columns in applicants table.
Code4Good-UWMadison/Coding4Good-Site pull request #34
Opened 2020-10-23 17:38 UTC by jeffreyzhao5618

2020-11-02 21:54 UTC, jialuogao reviewed
For delimiter, please change to Tab (\t) thus TVS instead of CVS since it works well in both excel and google sheet for copying

2020-11-02 22:01 UTC, jialuogao commented on views/project/applicants.ejs
> +                                copyString += ","
Change to `\t` would result in better experience

2020-11-02 22:04 UTC, jialuogao commented on views/project/applicants.ejs
> +
Also add another option (check box) to choose if copy the headers please, copy with multiple column really needs header

2020-11-02 22:05 UTC, jialuogao requested changes
Very good overall, only 2 minor things to fix

2020-11-04 20:27 UTC, jeffreyzhao5618 reviewed
Added copy headers option to copy table.
Copy table now copies in TSV format.
Changed appearance of copy table.

2020-11-07 00:59 UTC, jialuogao approved these changes
Good, did some minor layout changes

2020-11-07 00:59 UTC, closed without merging